{% set name = "elfio" %}
{% set version = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/serge1/ELFIO/archive/refs/tags/Release_{{ version }}.tar.gz
  sha256: e4ebc9ce3d6916461bc3e7765bb45e6210f0a9b93978bf91e59b05388c024489

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

    # Only required for building tests
    - boost  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/elfio/elfio.hpp  # [unix]
    - if not exist %PREFIX%\include\elfio\elfio.hpp exit 1  # [win]

about:
  home: https://serge1.github.io/ELFIO
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: ELF (Executable and Linkable Format) reader and producer implemented as a header only C++ library
  doc_url: http://elfio.sourceforge.net/elfio.pdf
  dev_url: https://github.com/serge1/ELFIO

extra:
  recipe-maintainers:
    - matthiasdiener
    - awvwgk
